name: kalinar
description: A new Flutter project.
publish_to: "none"

version: 0.5.7+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  flutter_spinkit: ^5.2.0
  elegant_notification: ^1.11.0

  uuid:
  collection:
  url_launcher:
  in_app_update:
  store_checker:
  flutter_flavor:
  overlay_support:
  keyboard_dismisser:
  cached_network_image:
  sentry_flutter: ^7.6.1
  shared_preferences: ^2.0.18
  
  http: ^1.1.0
  intl: ^0.18.1
  go_router: ^10.1.0

  google_sign_in: ^6.1.3
  firebase_core: ^2.7.1
  firebase_messaging: ^14.3.0
  firebase_auth: ^4.6.2
  firebase_ui_auth: ^1.4.2
  firebase_ui_oauth_google: ^1.2.2
  firebase_ui_localizations: ^1.5.0

  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

  flutter_gravatar: ^2.0.2

  flutter_form_builder:
  form_builder_validators:
  form_builder_extra_fields:
  flutter_typeahead:
  flutter_spinbox:
  desktop_drop:
  file_picker:
  mime:
  flutter_iconpicker:
    # git: 
    #   url: https://github.com/kechankrisna/FlutterIconPicker.git
    #   ref: hotfix
  dropdown_button2: ^2.3.8

  fade_shimmer: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0

  diacritic: ^0.1.3
  expandable_group: ^0.0.8
  grouped_list: ^5.1.2
  filter_list: ^1.0.2
  flutter_side_menu: ^0.4.0
  easy_search_bar: ^2.5.0

  flutter_quill: ^7.4.1
  flutter_quill_extensions: ^0.4.1

  rounded_loading_button: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  custom_pop_up_menu: ^1.2.4
  just_the_tooltip:
  square_progress_bar:
  animations: ^2.0.7
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  timeline_tile: ^2.0.0
  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  timeago_flutter: ^3.4.0
  multiselect: ^0.1.0
  flutter_tagging_plus: ^4.0.1

dependency_overrides:
  http: ^1.1.0
  intl: ^0.18.1
  flutter_svg: ^2.0.5
  flutter_chips_input: 
     git: https://github.com/bradintheusa/flutter_chips_input

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:
  msix:
  dependency_validator:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon/icon.png
    # - assets/images/
    # - assets/images/kali/

  fonts:
    - family:  Kalinar
      fonts:
       - asset: assets/fonts/Kalinar.ttf

# flutter pub run msix:create
msix_config:
  display_name: Kalinar
  publisher: CN=F507F5FC-3669-4046-BDE3-4F9D28238B0E
  publisher_display_name: Jonas Curth
  identity_name: 62592JonasCurth.5320319B39ACD
  logo_path: assets/app_icon/play_store_512.png
  capabilities: internetClient
  languages: de-de
  store: true
  app_installer:  
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
