name: kalinar
description: A new Flutter project.
publish_to: "none"

version: 0.5.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  in_app_update: ^4.0.1
  store_checker: ^1.1.0

  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  firebase_ui_auth: ^1.1.3
  firebase_ui_oauth_google: ^1.0.10
  google_sign_in: ^5.4.2
  firebase_ui_localizations: ^1.0.1

  http: ^0.13.5
  intl: ^0.17.0
  go_router: ^6.0.6
  flutter_riverpod: ^2.1.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  uuid: ^3.0.6
  flutter_flavor: ^3.1.1
  collection:
  sentry_flutter: ^6.16.1
  flutter_staggered_grid_view: ^0.6.2

  shared_preferences: ^2.0.15
  flutter_gravatar: ^2.0.2

  firebase_auth_desktop:
    git:
      url: https://github.com/NirmalAriyathilake/flutterfire_desktop.git
      path: packages/firebase_auth/firebase_auth_desktop

  firebase_core_desktop:
    git:
      url: https://github.com/NirmalAriyathilake/flutterfire_desktop.git
      path: packages/firebase_core/firebase_core_desktop

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  flutter_form_builder: ^7.2.0
  form_builder_image_picker: ^3.1.0
  form_builder_validators: ^8.1.1
  form_builder_extra_fields: ^8.3.0
  desktop_drop: ^0.4.0
  mime: ^1.0.2
  flutter_touch_spin: ^2.0.0
  file_picker:
  flutter_typeahead: ^4.1.1
  cross_file: ^0.3.3+2

  flutter_iconpicker: #^3.2.2
    git: 
      url: https://github.com/kechankrisna/FlutterIconPicker.git
      ref: hotfix

  flutter_quill: ^6.3.3
  flutter_quill_extensions: ^0.1.0

  rounded_loading_button: ^2.1.0
  modal_bottom_sheet: ^3.0.0-pre
  dotted_border: ^2.0.0+2
  salomon_bottom_bar: ^3.3.1
  custom_pop_up_menu: ^1.2.4
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  flutter_speed_dial: ^6.2.0
  flutter_layout_grid: ^2.0.1
  just_the_tooltip:
  square_progress_bar:
  animations: ^2.0.7
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  fancy_shimmer_image: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  cached_network_image: ^3.2.3
  timeline_tile: ^2.0.0
  auto_size_text: ^3.0.0

dependency_overrides:
  flutter_chips_input: 
     git: https://github.com/bradintheusa/flutter_chips_input

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  msix: ^3.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon/icon.png

# flutter pub run msix:create
msix_config:
  display_name: Kalinar
  publisher: CN=F507F5FC-3669-4046-BDE3-4F9D28238B0E
  publisher_display_name: Jonas Curth
  identity_name: 62592JonasCurth.5320319B39ACD
  logo_path: assets/app_icon/play_store_512.png
  capabilities: internetClient
  languages: de-de
  store: true
  app_installer:  
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false