// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu3iRfvSdv6ZVx_Ml5ynF572cXtlbeWGQ',
    appId: '1:718959006853:web:3befbea7a01568341185ec',
    messagingSenderId: '718959006853',
    projectId: 'kalinar-app',
    authDomain: 'kalinar-app.firebaseapp.com',
    storageBucket: 'kalinar-app.appspot.com',
    measurementId: 'G-63JKTFLBPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3ClRfwA8NCUYx1eZO9lIlhSfCxV4sh4',
    appId: '1:718959006853:android:440f20e9684a83971185ec',
    messagingSenderId: '718959006853',
    projectId: 'kalinar-app',
    storageBucket: 'kalinar-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKxV6XoqGswCqnM-hj7H0sOVn1ok_JeEI',
    appId: '1:718959006853:ios:6e80392cbee4c7531185ec',
    messagingSenderId: '718959006853',
    projectId: 'kalinar-app',
    storageBucket: 'kalinar-app.appspot.com',
    iosClientId: '718959006853-svbkm1a0imbm0qajbnjo4a11c772f5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKxV6XoqGswCqnM-hj7H0sOVn1ok_JeEI',
    appId: '1:718959006853:ios:6e80392cbee4c7531185ec',
    messagingSenderId: '718959006853',
    projectId: 'kalinar-app',
    storageBucket: 'kalinar-app.appspot.com',
    iosClientId: '718959006853-svbkm1a0imbm0qajbnjo4a11c772f5sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.hero',
  );
}
