name: Build Flutter for Android and publish to Play Store

on: 
  push:
    paths: 
      - ".github/workflows/android.yml"
  # branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        cache: true
        
    - name: Restore packages
      working-directory: ./Client
      run: flutter pub get
      
    - name: Download Android keystore
      run: echo "${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}" | base64 --decode > /tmp/key.jks
      
    - name: Create key.properties
      run: |
        rm -f -- ./Client/android/key.properties
        touch ./Client/android/key.properties
        echo "storeFile=/tmp/key.jks" >> ./Client/android/key.properties
        echo "storePassword=${{ secrets.GOOGLE_PLAY_SIGNING_KEY_STORE_PASSWORD }}" >> ./Client/android/key.properties
        echo "keyPassword=${{ secrets.GOOGLE_PLAY_SIGNING_KEY_PASSWORD }}" >> ./Client/android/key.properties
        echo "keyAlias=${{ vars.GOOGLE_PLAY_SIGNING_KEY_ALIAS }}" >> ./Client/android/key.properties
    
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.github_token}} 
    
    - name: Build for Android
      working-directory: ./Client
      run: flutter build appbundle --dart-define=SENTRY_DSN=${{ vars.SENTRY_DNS }} --flavor=prod --release --no-tree-shake-icons --build-number=${BUILD_NUMBER}
        
    - uses: actions/upload-artifact@v2
      name: Upload android appbundle artifact 
      with:
        name: appbundle
        path: ./Client/build/app/outputs/bundle/prodRelease/app-prod-release.aab
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: appbundle
    - run: ls
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1.1.1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: dev.curth.hero
        releaseFiles: ./app-prod-release.aab
        track: internal
