name: Build Client for Android and publish to Play Store

on: 
  push:
    paths: 
      - ".github/workflows/app.yml"
      - "Client/**"
    branches: [ "main" ]
  pull_request:
    paths: 
      - ".github/workflows/app.yml"
      - "Client/**"
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: web
    
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        cache: true

    - name: Restore packages
      working-directory: ./Client
      run: flutter pub get

    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ghcr.io/kalinarapp/web

    - name: Build for Web
      working-directory: ./Client
      run: flutter build web --dart-define=SENTRY_DSN=${{ vars.SENTRY_DNS }} --release --no-tree-shake-icons
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: ./Client
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        cache: true
        
    - name: Restore packages
      working-directory: ./Client
      run: flutter pub get
      
    - name: Download Android keystore
      run: echo "${{ secrets.GOOGLE_PLAY_SIGNING_KEY }}" | base64 --decode > /tmp/key.jks
      
    - name: Create key.properties
      run: |
        rm -f -- ./Client/android/key.properties
        touch ./Client/android/key.properties
        echo "storeFile=/tmp/key.jks" >> ./Client/android/key.properties
        echo "storePassword=${{ secrets.GOOGLE_PLAY_SIGNING_KEY_STORE_PASSWORD }}" >> ./Client/android/key.properties
        echo "keyPassword=${{ secrets.GOOGLE_PLAY_SIGNING_KEY_PASSWORD }}" >> ./Client/android/key.properties
        echo "keyAlias=${{ vars.GOOGLE_PLAY_SIGNING_KEY_ALIAS }}" >> ./Client/android/key.properties
    
    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.github_token}} 
    
    - name: Build for Android
      working-directory: ./Client
      run: flutter build appbundle --dart-define=SENTRY_DSN=${{ vars.SENTRY_DNS }} --flavor=prod --release --no-tree-shake-icons --build-number=${BUILD_NUMBER}

    - uses: actions/upload-artifact@v2
      name: Upload android appbundle artifact 
      with:
        name: appbundle
        path: ./Client/build/app/outputs/bundle/prodRelease/app-prod-release.aab
        
  release-android:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build-android]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: appbundle
    - name: Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1.1.1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: dev.curth.hero
        releaseFiles: ./app-prod-release.aab
        track: internal

       
  production-android:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [release-android]
    environment:
        name: Production
    steps:
    - name: Promote release to open testing
      uses: kevin-david/promote-play-release@v1.0.0
      with:
        service-account-json-raw: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        package-name: dev.curth.hero
        from-track: internal
        to-track: beta
