name: Build and Test Project

on:
  push:
    paths:
      - .github/workflows/dotnet.yml
      - Server/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/dotnet.yml
      - Server/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "Server/Hero.Server/Hero.Server.csproj"
    - name: Build
      run: dotnet build "Server/Hero.Server.sln" --no-restore
#    - name: Test
#      run: dotnet test "Hero.Server.sln" --no-build --verbosity normal
