name: Build and Test Project

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/kalinar-server.yml
      - NewServer/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/kalinar-server.yml
      - NewServer/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-New

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore "NewServer/Kalinar.sln"
    - name: Build
      run: dotnet build "NewServer/Kalinar.sln" --no-restore
    - name: Test
      run: dotnet test "NewServer/Kalinar.sln" --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build]
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to the Container registry
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: ./NewServer
        file: NewServer/Kalinar/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}