name: Build Flutter for Windows and publish to Windows Store

on: 
  push:
    paths: 
      - ".github/workflows/windows.yml"
  # branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Support longpaths
      run: git config --system core.longpaths true

    - name: Install Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        cache: true
        
    - name: Restore packages
      working-directory: ./Client
      run: flutter pub get
      
    - name: Build for Windows
      working-directory: ./Client
      run: |
        flutter config --enable-windows-desktop
        flutter pub run msix:create
        
    - uses: actions/upload-artifact@v2
      name: Upload windows msix artifact 
      with:
        name: Windows MSIX
        path: ./Client/build/windows/runner/Release/kalinar.msix
        
    - uses: actions/upload-artifact@v2
      name: Upload android appbundle artifact 
      with:
        name: msix
        path: ./Client/build/windows/runner/Release/kalinar.msix
        
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: msix
    - name: Windows Store Publish
      uses: isaacrlevin/windows-store-action@1.0
      with:
        tenant-id: ${{ vars.WINDOWS_STORE_TENANT_ID }}
        client-id: ${{ vars.WINDOWS_STORE_CLIENT_ID }}
        client-secret: ${{ secrets.WINDOWS_STORE_CLIENT_SECRET }}
        app-id: ${{ vars.WINDOWS_STORE_APP_ID }}
        package-path: .
    
